add_newline = false
palette = "catppuccin_mocha"
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

format = """

$username ó°œ¥ $directory $git_branch
$character"""

[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[î©± ó°„›](subtext0) â¯](mauve)"
error_symbol = "[[ï€ ó°„›](red) â¯](red)"
vimcmd_symbol = "[ó°„› â®](subtext1)" # For use with zsh-vi-mode

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: sky"
symbol = "ó°˜¬"
truncation_length = 12
format = "ó°œ¥ [î‚¶](bold fg:sky)[$symbol $branch(:$remote_branch)](fg:black bg:sky)[î‚´ ](bold fg:sky)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[îˆ±  PICKING](bold sky)"

[git_status]
conflicted = "[ï•™](mauve) "
ahead = "ï•™"
behind = " â‡£ "
diverged = " â‡µ "
untracked = "[?](mauve)"
stashed = "ğŸ“¦"
modified = "[ğŸ“](mauve)"
# staged = '[++\($count\)](mauve)'
renamed = " ó°‘• "
deleted = "[îª ](mauve)"

# [git_status]
# conflicted = " ï•™ "
# ahead = " â‡¡ "
# stashed = " ï”º "
# modified = " ï„ "
# staged = '[++\($count\)](green)'


[line_break]
disabled = false

[username]
style_user = "bold bg:mauve fg:black"
style_root = "red bold"
format = '[î‚¶](bold fg:mauve)[ïŒ” $user](bold bg:mauve fg:black)[î‚´](bold fg:mauve)'
disabled = false
show_always = true

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:teal fg:black"
truncation_length = 6
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:teal)[ó°‰‹ $path]($style)[î‚´](bold fg:teal)'

[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "

# [hostname]
# ssh_only = false
# format =  "[â€¢$hostname](bg:cyan bold fg:black)[î‚´](bold fg:cyan)"
# trim_at = ".companyname.com"
# disabled = false


# [memory_usage]
# disabled = true
# threshold = -1
# symbol = " "
# style = "bold dimmed green"

# [time]
# disabled = true
# format = 'ğŸ•™[\[ $time \]]($style) '
# time_format = "%T"


# [cmd_duration]
# min_time = 0
# format = '[î‚¶](bold fg:yellow)[ó°ª¢ $duration](bold bg:yellow fg:black)[î‚´](bold fg:yellow)'
